from preferences import PREFERENCES_PATH, UserPreferences


_preferences = UserPreferences(PREFERENCES_PATH)
_preferences.load()
_theme = _preferences.get_theme_preferences()

APP_BACKGROUND = _theme["APP_BACKGROUND"]
SURFACE = _theme["SURFACE"]
SURFACE_MUTED = _theme["SURFACE_MUTED"]

FIELD_BACKGROUND = _theme["FIELD_BACKGROUND"]
FIELD_HOVER = _theme["FIELD_HOVER"]
FIELD_FOCUS = _theme["FIELD_FOCUS"]
FIELD_DISABLED = _theme["FIELD_DISABLED"]

PRIMARY = _theme["PRIMARY"]
PRIMARY_LIGHT = _theme["PRIMARY_LIGHT"]
PRIMARY_DARK = _theme["PRIMARY_DARK"]
PRIMARY_HOVER = _theme["PRIMARY_HOVER"]

BUTTON_SOFT = _theme["BUTTON_SOFT"]
BUTTON_SOFT_HOVER = _theme["BUTTON_SOFT_HOVER"]
BUTTON_DISABLED = _theme["BUTTON_DISABLED"]
DELETE_SOFT = _theme["DELETE_SOFT"]
DELETE_HOVER = _theme["DELETE_HOVER"]

SIDEBAR_BACKGROUND = _theme["SIDEBAR_BACKGROUND"]
SIDEBAR_TILE = _theme["SIDEBAR_TILE"]
SIDEBAR_TILE_HOVER = _theme["SIDEBAR_TILE_HOVER"]
SIDEBAR_TILE_SELECTED = _theme["SIDEBAR_TILE_SELECTED"]

TEXT_DARK = _theme["TEXT_DARK"]
TEXT_MUTED = _theme["TEXT_MUTED"]
TEXT_LIGHT = _theme["TEXT_LIGHT"]
TEXT_DISABLED = _theme["TEXT_DISABLED"]

BORDER = _theme["BORDER"]
BORDER_SOFT = _theme["BORDER_SOFT"]
LIST_HOVER = _theme["LIST_HOVER"]

CONTROL_RADIUS = 10
